Feature functions
SemRoCo/giskardpy pull request #161
Opened 2024-08-08 08:02 UTC by maltehue

This introduces Feature Function Constraints (Goals) and Monitors.
It also includes a notebook showcasing some capabilities of Giskard including the advantages of feature functions.
The Notebook will be extended to Environment Manipulation and Monitors.

2024-08-21 15:54 UTC, ichumuh requested changes

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/goals/pointing.py
> -        root_P_goal_point = symbol_manager.get_expr(f'god_map.motion_goal_manager.motion_goals[\'{str(self)}\']'
revert

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +        self.last_execution_state = result.execution_state
this is probably better placed in _send_action_goal/get_result

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +    def get_end_motion_reason(self, move_result: MoveResult = None, show_all=False):
Optional[MoveResult]

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +    def get_end_motion_reason(self, move_result: MoveResult = None, show_all=False):
show_all: bool

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +            if monitor.monitor_class == 'CancelMotion':
`CancelMotion.__name__`

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +            if monitor.monitor_class == 'EndMotion':
same as above

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +            if monitor.monitor_class == 'CancelMotion':
there might be multiple end/cancel monitors

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +            if monitor.monitor_class == 'CancelMotion':
there is also a bug/problem that i have at other places too. monitors which inherit from cancel monitor don't evaluate to true here

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +    def get_end_motion_reason(self, move_result: MoveResult = None, show_all=False):
what is result type?

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +    def get_end_motion_reason(self, move_result: MoveResult = None, show_all=False):
doc string

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +                result[monitor.name] = state
`{monitor.name: state for monitor, state in zip(execution_state.monitors, execution_state.monitor_state)}`

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +            if monitor.monitor_class == 'CancelMotion':
cancelMotion_idx is not used

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +            if monitor.monitor_class == 'CancelMotion':
ever heard of enumerate?

2024-08-21 15:54 UTC, ichumuh commented on src/giskardpy/python_interface/python_interface.py
> +                if monitor.name in start_condition and state == 0:
you should look for `f'\'{monitor.name}\''` in the conditions, otherwise it might break with monitors named, e.g., "and"

2024-08-22 07:24 UTC, maltehue commented on .github/workflows/reusable_robot_ci.yml
> +          ref: monitor_result_feedback
I can change that when we merge the PR for giskard msgs

2024-08-22 09:10 UTC, merged