Cartesian position straight
SemRoCo/giskardpy pull request #60
Opened 2020-09-22 14:56 UTC by J-Schaefer

Add class CartesianPositionStraight to ensure a straight movement

Also:

  * Adding a test to open all drawers
  * Add prefix in basic constraints to enable multiple use of the constraints
  * already replaced CartesianPosition by the new class
  * Added some new conversion functions to tf_wrapper

2020-09-22 17:20 UTC, ichumuh requested changes

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/constraints.py
> +        root_V_start = w.point3(*tf.transform_stamped_to_pq(tf.lookup_transform(self.root, self.tip))[0])
```
asdf = tf.lookup_transform(self.root, self.tip)
w.point3(asdf.position.x,
asdf.position.y,
asdf.position.z)
```

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/constraints.py
> +        self.add_debug_vector(u'start_point', root_P_goal)
no debug

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/constraints.py
> +        # FIXME: type error. Mixed calc with Vector3 and SX (expression)
fixme?

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/constraints.py
> +        self.constraints.append(CartesianPositionStraight(god_map=god_map,
create a `CartesianPoseStraight` for now

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/python_interface.py
> +            constraint.type = u'CartesianPositionStraight'
add functions for straight option

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/qp_problem_builder.py
> +        self.debug_print(np_H, A, lb, ub, lbA, ubA, g, xdot_full)
no debug

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/tfwrapper.py
> +def pose_to_pq(msg):
rename to pose_to_numpy

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/tfwrapper.py
> +    """
use my comment style

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/tfwrapper.py
> +    """Conversion from geometric ROS messages into SE(3)
rename to `msg_to_homogeneous_matrix`

2020-09-22 17:20 UTC, ichumuh commented on test/test_integration_pr2.py
> +        joint_name = [str(item).decode("utf-8").replace(u'handle', u'main_joint').encode("utf-8") for item in handle_name]
too complicated.

2020-09-22 17:20 UTC, ichumuh commented on test/test_integration_pr2.py
> +            rospy.loginfo('=== Opening drawer: ' + str(i_handle_name).decode('utf-8') + ' ===')
`logging.loginfo`
use normal unicode

2020-09-22 17:20 UTC, ichumuh commented on src/giskardpy/constraints.py
> +        root_V_start = w.point3(*tf.transform_stamped_to_pq(tf.lookup_transform(self.root, self.tip))[0])
use `get_input_PoseStamped` and write tf pose to godmap in init

2020-09-24 15:20 UTC, J-Schaefer commented
I changed everything. Free for testing now!

2021-01-04 14:55 UTC, J-Schaefer commented
Is this still current? There are a few conflicts but only regarding names. Did you have issues last time, @ichumuh ??
The tests work on my system although ```test_CartesianPoseStraight``` freezes and only works when added in the function ```set_translation_goal``` in ```python_interface```.

2021-01-04 15:28 UTC, ichumuh commented
I didn't merge it because of the error i posted here: https://github.com/SemRoCo/giskard_msgs/pull/14
Probably didn't post the error here by accident.
Not sure if that is fixed now. If you merge with devel, I'll try again.

2021-01-05 08:45 UTC, J-Schaefer commented
I remember, you mentioned before. I'll check.

2021-01-05 12:17 UTC, merged